---
title: "Electricity Time Series Project"
output: html_document
date: "2023-05-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

path <- "/Users/alisonwong/git/electricity-time-series"
knitr::opts_knit$set(root.dir = path)
setwd(path)

# Load Packages 
library(readxl)
library(tidyverse)
library(latex2exp)
library(forecast)
```

# Read in data and perform data cleaning and wrangling 
```{r}
# Read data 
energy <- read.csv("energy-ca.csv")

# Subset data to select columns we need: Year, Month, State, Megawatts (sold)
energy_df <- subset(energy, select = c("X", "X.1", "X.2", "X.16"))
energy_df <- energy_df[-c(1,2),] # remove first two rows (unnecessary as these rows were the result of a small issue when importing the file)

# Add column names
colnames(energy_df) <- c("Year", "Month", "State", "Megawatts")
table(grepl("CA", energy_df$State)) # check the amount of times in which "CA" appears in the "X.2" column which corresponds to the respective state

# Subset data to select California 
energy_df <- energy_df[energy_df$State == "CA",]

# Get rid of empty rows
row.names(energy_df) <- NULL

# Check the amount of times in which the State column equals "CA". Since this number, 158, matches with the earlier number, we have support to say no important data was lost
table(grepl("CA", energy_df$State))
```

# Arrange data to create a time series object
```{r}
# Change to integers
energy_df$Year <- as.integer(energy_df$Year)
energy_df$Month <- as.integer(energy_df$Month)
energy_df$Megawatts <- as.integer(gsub(",", "", energy_df$Megawatts))

# Arrange energy_df in ascending order of time
energy_df <- energy_df %>%
  arrange(Year, Month)
head(energy_df)

# Remove the 2023 year as only Jan and Feb data is present
energy_df <- energy_df[energy_df$Year != 2023,]

# Time series model 
energy_ts <- ts(energy_df[,4], start= 2010, frequency = 12)
ts.plot(energy_ts, 
        main = "Electricity (Megawatts) Sold with Yearly Average", 
        xlab = "Year", 
        ylab = "Electricity Sold in Megawatts")
```

# Perform time series analysis

Compute yearly average $\hat m_j$ over all months a $\hat m_j=\frac{1}{12}\sum_{k=1}^{12}x_{j,k}$ and eliminate the yearly trend
```{r}
# Get overall trend by moving average window of 12
m_t = ma(energy_ts, order = 12, centre = T)
ts.plot(energy_ts, xlab = "Year", ylab = "Electricity Sold in Megawatts", main = "")
lines(m_t, col = "red")

# Overall trend
ts.plot(m_t, xlab = "Year", ylab = "Electricity Sold in Megawatts", main = "")

# Detrend only
detrend = energy_ts - m_t
```

Seasonality
```{r}
# Plot new time series that clearly exposes seasonality
ts.plot(detrend, xlab = "Year", ylab = "Electricity Sold in Megawatts", main = "")

# Get seasonality from detrended time series
s_t <- t(matrix(data = detrend, nrow = 12))

# Monthly seasonality: use matrix of 12 rows
s_t <- colMeans(s_t, na.rm = T)
ts.plot(rep(s_t,12), xlab = "Year", ylab = "Electricity Sold in Megawatts", main = "")
```

Residuals & White Noise
```{r}
# Decomposed time series by detrending and deseasonalizing
# Extract white noise
z_t <- energy_ts - m_t - s_t
ts.plot(z_t, xlab = "Year", ylab = "Electricity Sold in Megawatts", main = "")

# Plot time series, ACF, histogram of white noise
checkresiduals(z_t)
```

Compute ACF of the time series
```{r}
acf(energy_ts) # not sure why the x axis is wrong
```


